---
title: "Using PurpleAir API"
output: html_notebook
---

# get data from my PA-II sensor on my back deck

```{r}
# packages

#install.packages(c("httr", "jsonlite"))
library(httr)
library(jsonlite)
library(tidyverse)

```

# make a request from the PurpleAir API for my sensor

```{r}
# help from https://rdrr.io/cran/httr/f/vignettes/quickstart.Rmd

r <- GET("https://api.purpleair.com/v1/sensors/154517", 
         query = list(api_key = '6B64127F-1D79-11ED-8561-42010A800005'))

r
# rawToChar() will convert raw data 
# to char and store in response variable
response <- rawToChar(r$content)

# parse the json
rawdata = fromJSON(response)

# what was the temp reading? confirm good - seems off from the map value
# and the map widget mentions a conversion - wonder what it is
# found this https://community.purpleair.com/t/the-purpleair-utility/673
# T The temperature inside the sensor’s housing - this temperature reading # will be approximately 8 degrees higher than ambient conditions due to # heat generated by the WiFi module in the sensor’s control board.

# H The humidity inside the sensor’s housing - this humidity reading will # be approximately 4% lower than ambient conditions due to heat generated # by the WiFi module in the sensor’s control board.
rawdata$sensor$temperature - 8

# correct value to match map
rawdata$sensor$stats$pm2.5_10minute


# to get to the sensor data can build a DF from the sensor data blob
data <- data.frame(rawdata$sensor)
data

# not sure that's useful but?


# example URL for getting a few fields
# https://api.purpleair.com/v1/sensors/37403?sensor_index=37403&fields=pm2.5_30minute%2Ctemperature%2Chumidity

```

# cool, now let's pull some historical data

```{r}
# consult API for more params
# https://api.purpleair.com/#api-sensors-get-sensor-history
r <- GET("https://api.purpleair.com/v1/sensors/154517/history/csv", 
         query = list(api_key = '6B64127F-1D79-11ED-8561-42010A800005'))

r
fromJSON(rawToChar(r$content))

# oh, they restricted the access to this
# see https://community.purpleair.com/t/historical-api-endpoints-are-now-restricted/1557

# I can ask for permission but for now I will wait


```

# for PM2.5 need to do a conversion to generate the standard AQI
## note that PurpleAir maps show the 10 min avg value, converted to AQI

```{r}

# going to need a function



```


